 
# The server address to the MQTT broker to connect to and read 
# messages from the given topic.
mqtt:
  server: ""
  topic: "sensors"

# The Slack webhook url to post messages to when alarm is triggered.
slack_webhook_url: = ""

# Sensor readings taken from the MQTT broker will be posted to this 
# addess for persistence
save_sensor_url: ""

